// Mocks generated by Mockito 5.4.4 from annotations
// in mobile_service_manager/test/test_config.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i10;

import 'package:mobile_service_manager/database/object_box.dart' as _i4;
import 'package:mobile_service_manager/models/brand.dart' as _i5;
import 'package:mobile_service_manager/models/fault.dart' as _i7;
import 'package:mobile_service_manager/models/service_item.dart' as _i8;
import 'package:mobile_service_manager/models/technician.dart' as _i6;
import 'package:mobile_service_manager/objectbox.g.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:objectbox/src/native/store.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBox_0<T> extends _i1.SmartFake implements _i2.Box<T> {
  _FakeBox_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_1<T> extends _i1.SmartFake implements _i3.Future<T> {
  _FakeFuture_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ObjectBox].
///
/// See the documentation for Mockito's code generation for more information.
class MockObjectBox extends _i1.Mock implements _i4.ObjectBox {
  MockObjectBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Box<_i5.Brand> get brandBox => (super.noSuchMethod(
        Invocation.getter(#brandBox),
        returnValue: _FakeBox_0<_i5.Brand>(
          this,
          Invocation.getter(#brandBox),
        ),
      ) as _i2.Box<_i5.Brand>);

  @override
  set brandBox(_i2.Box<_i5.Brand>? _brandBox) => super.noSuchMethod(
        Invocation.setter(
          #brandBox,
          _brandBox,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Box<_i6.Technician> get technicianBox => (super.noSuchMethod(
        Invocation.getter(#technicianBox),
        returnValue: _FakeBox_0<_i6.Technician>(
          this,
          Invocation.getter(#technicianBox),
        ),
      ) as _i2.Box<_i6.Technician>);

  @override
  set technicianBox(_i2.Box<_i6.Technician>? _technicianBox) =>
      super.noSuchMethod(
        Invocation.setter(
          #technicianBox,
          _technicianBox,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Box<_i7.Fault> get faultBox => (super.noSuchMethod(
        Invocation.getter(#faultBox),
        returnValue: _FakeBox_0<_i7.Fault>(
          this,
          Invocation.getter(#faultBox),
        ),
      ) as _i2.Box<_i7.Fault>);

  @override
  set faultBox(_i2.Box<_i7.Fault>? _faultBox) => super.noSuchMethod(
        Invocation.setter(
          #faultBox,
          _faultBox,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Box<_i8.ServiceItem> get serviceItemBox => (super.noSuchMethod(
        Invocation.getter(#serviceItemBox),
        returnValue: _FakeBox_0<_i8.ServiceItem>(
          this,
          Invocation.getter(#serviceItemBox),
        ),
      ) as _i2.Box<_i8.ServiceItem>);

  @override
  set serviceItemBox(_i2.Box<_i8.ServiceItem>? _serviceItemBox) =>
      super.noSuchMethod(
        Invocation.setter(
          #serviceItemBox,
          _serviceItemBox,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get dbPath => (super.noSuchMethod(
        Invocation.getter(#dbPath),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#dbPath),
        ),
      ) as String);

  @override
  set dbPath(String? _dbPath) => super.noSuchMethod(
        Invocation.setter(
          #dbPath,
          _dbPath,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int insertBrand(_i5.Brand? brand) => (super.noSuchMethod(
        Invocation.method(
          #insertBrand,
          [brand],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i5.Brand? getBrand(int? id) => (super.noSuchMethod(Invocation.method(
        #getBrand,
        [id],
      )) as _i5.Brand?);

  @override
  List<_i5.Brand> getAllBrands() => (super.noSuchMethod(
        Invocation.method(
          #getAllBrands,
          [],
        ),
        returnValue: <_i5.Brand>[],
      ) as List<_i5.Brand>);

  @override
  bool deleteBrand(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteBrand,
          [id],
        ),
        returnValue: false,
      ) as bool);

  @override
  int insertTechnician(_i6.Technician? technician) => (super.noSuchMethod(
        Invocation.method(
          #insertTechnician,
          [technician],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i6.Technician? getTechnician(int? id) =>
      (super.noSuchMethod(Invocation.method(
        #getTechnician,
        [id],
      )) as _i6.Technician?);

  @override
  List<_i6.Technician> getAllTechnicians() => (super.noSuchMethod(
        Invocation.method(
          #getAllTechnicians,
          [],
        ),
        returnValue: <_i6.Technician>[],
      ) as List<_i6.Technician>);

  @override
  bool deleteTechnician(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTechnician,
          [id],
        ),
        returnValue: false,
      ) as bool);

  @override
  int insertFault(_i7.Fault? fault) => (super.noSuchMethod(
        Invocation.method(
          #insertFault,
          [fault],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i7.Fault? getFault(int? id) => (super.noSuchMethod(Invocation.method(
        #getFault,
        [id],
      )) as _i7.Fault?);

  @override
  List<_i7.Fault> getAllFaults() => (super.noSuchMethod(
        Invocation.method(
          #getAllFaults,
          [],
        ),
        returnValue: <_i7.Fault>[],
      ) as List<_i7.Fault>);

  @override
  bool deleteFault(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteFault,
          [id],
        ),
        returnValue: false,
      ) as bool);

  @override
  int insertServiceItem(_i8.ServiceItem? item) => (super.noSuchMethod(
        Invocation.method(
          #insertServiceItem,
          [item],
        ),
        returnValue: 0,
      ) as int);

  @override
  List<_i8.ServiceItem> getAllServiceItems() => (super.noSuchMethod(
        Invocation.method(
          #getAllServiceItems,
          [],
        ),
        returnValue: <_i8.ServiceItem>[],
      ) as List<_i8.ServiceItem>);

  @override
  List<_i8.ServiceItem> getTrashServiceItems() => (super.noSuchMethod(
        Invocation.method(
          #getTrashServiceItems,
          [],
        ),
        returnValue: <_i8.ServiceItem>[],
      ) as List<_i8.ServiceItem>);

  @override
  List<_i8.ServiceItem> getTodayServiceItems() => (super.noSuchMethod(
        Invocation.method(
          #getTodayServiceItems,
          [],
        ),
        returnValue: <_i8.ServiceItem>[],
      ) as List<_i8.ServiceItem>);

  @override
  bool deleteServiceItem(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteServiceItem,
          [id],
        ),
        returnValue: false,
      ) as bool);

  @override
  void closeStore() => super.noSuchMethod(
        Invocation.method(
          #closeStore,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Store].
///
/// See the documentation for Mockito's code generation for more information.
class MockStore extends _i1.Mock implements _i2.Store {
  MockStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get directoryPath => (super.noSuchMethod(
        Invocation.getter(#directoryPath),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#directoryPath),
        ),
      ) as String);

  @override
  _i10.ByteData get reference => (super.noSuchMethod(
        Invocation.getter(#reference),
        returnValue: _i10.ByteData(0),
      ) as _i10.ByteData);

  @override
  bool isClosed() => (super.noSuchMethod(
        Invocation.method(
          #isClosed,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Box<T> box<T>() => (super.noSuchMethod(
        Invocation.method(
          #box,
          [],
        ),
        returnValue: _FakeBox_0<T>(
          this,
          Invocation.method(
            #box,
            [],
          ),
        ),
      ) as _i2.Box<T>);

  @override
  R runInTransaction<R>(
    _i2.TxMode? mode,
    R Function()? fn,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #runInTransaction,
          [
            mode,
            fn,
          ],
        ),
        returnValue: _i9.dummyValue<R>(
          this,
          Invocation.method(
            #runInTransaction,
            [
              mode,
              fn,
            ],
          ),
        ),
      ) as R);

  @override
  _i3.Future<R> runInTransactionAsync<R, P>(
    _i2.TxMode? mode,
    _i11.TxAsyncCallback<R, P>? callback,
    P? param,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #runInTransactionAsync,
          [
            mode,
            callback,
            param,
          ],
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<R>(
                this,
                Invocation.method(
                  #runInTransactionAsync,
                  [
                    mode,
                    callback,
                    param,
                  ],
                ),
              ),
              (R v) => _i3.Future<R>.value(v),
            ) ??
            _FakeFuture_1<R>(
              this,
              Invocation.method(
                #runInTransactionAsync,
                [
                  mode,
                  callback,
                  param,
                ],
              ),
            ),
      ) as _i3.Future<R>);

  @override
  _i3.Future<R> runAsync<P, R>(
    _i11.RunAsyncCallback<P, R>? callback,
    P? param,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #runAsync,
          [
            callback,
            param,
          ],
        ),
        returnValue: _i9.ifNotNull(
              _i9.dummyValueOrNull<R>(
                this,
                Invocation.method(
                  #runAsync,
                  [
                    callback,
                    param,
                  ],
                ),
              ),
              (R v) => _i3.Future<R>.value(v),
            ) ??
            _FakeFuture_1<R>(
              this,
              Invocation.method(
                #runAsync,
                [
                  callback,
                  param,
                ],
              ),
            ),
      ) as _i3.Future<R>);

  @override
  bool awaitQueueCompletion() => (super.noSuchMethod(
        Invocation.method(
          #awaitQueueCompletion,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool awaitQueueSubmitted() => (super.noSuchMethod(
        Invocation.method(
          #awaitQueueSubmitted,
          [],
        ),
        returnValue: false,
      ) as bool);
}
