// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuYm7Rzl7-jBDhtiVEL_vLhKcb13VfRRY',
    appId: '1:314536848340:web:4d3188aa78375136cf0441',
    messagingSenderId: '314536848340',
    projectId: 'mobile-service-manager-7f748',
    authDomain: 'mobile-service-manager-7f748.firebaseapp.com',
    storageBucket: 'mobile-service-manager-7f748.firebasestorage.app',
    measurementId: 'G-CRJNTLPBWS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFHqEUlrXnn3zbB_aI8ackI1OB7912bLo',
    appId: '1:314536848340:ios:76da2281f7c178dbcf0441',
    messagingSenderId: '314536848340',
    projectId: 'mobile-service-manager-7f748',
    storageBucket: 'mobile-service-manager-7f748.firebasestorage.app',
    iosBundleId: 'com.soeminthein.mobileServiceManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuYm7Rzl7-jBDhtiVEL_vLhKcb13VfRRY',
    appId: '1:314536848340:web:10fde3cc3a3aac81cf0441',
    messagingSenderId: '314536848340',
    projectId: 'mobile-service-manager-7f748',
    authDomain: 'mobile-service-manager-7f748.firebaseapp.com',
    storageBucket: 'mobile-service-manager-7f748.firebasestorage.app',
    measurementId: 'G-1S9C4WV53G',
  );
}
