// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/brand.dart';
import 'models/fault.dart';
import 'models/technician.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 6515935303844240695),
      name: 'Brand',
      lastPropertyId: const obx_int.IdUid(2, 8306864908252591682),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2676313357904241468),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8306864908252591682),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 2909156849271409078),
      name: 'Technician',
      lastPropertyId: const obx_int.IdUid(2, 5162456155613190713),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1359050086352987301),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5162456155613190713),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 2744046361083258745),
      name: 'Fault',
      lastPropertyId: const obx_int.IdUid(2, 7680505461191604277),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5173973318705152563),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7680505461191604277),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(4, 2744046361083258745),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [7379893704960386916],
      retiredIndexUids: const [],
      retiredPropertyUids: const [500841533034733396, 2519385740775266796],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Brand: obx_int.EntityDefinition<Brand>(
        model: _entities[0],
        toOneRelations: (Brand object) => [],
        toManyRelations: (Brand object) => {},
        getId: (Brand object) => object.id,
        setId: (Brand object, int id) {
          object.id = id;
        },
        objectToFB: (Brand object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = Brand(id: idParam, name: nameParam);

          return object;
        }),
    Technician: obx_int.EntityDefinition<Technician>(
        model: _entities[1],
        toOneRelations: (Technician object) => [],
        toManyRelations: (Technician object) => {},
        getId: (Technician object) => object.id,
        setId: (Technician object, int id) {
          object.id = id;
        },
        objectToFB: (Technician object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = Technician(id: idParam, name: nameParam);

          return object;
        }),
    Fault: obx_int.EntityDefinition<Fault>(
        model: _entities[2],
        toOneRelations: (Fault object) => [],
        toManyRelations: (Fault object) => {},
        getId: (Fault object) => object.id,
        setId: (Fault object, int id) {
          object.id = id;
        },
        objectToFB: (Fault object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = Fault(id: idParam, name: nameParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Brand] entity fields to define ObjectBox queries.
class Brand_ {
  /// See [Brand.id].
  static final id = obx.QueryIntegerProperty<Brand>(_entities[0].properties[0]);

  /// See [Brand.name].
  static final name =
      obx.QueryStringProperty<Brand>(_entities[0].properties[1]);
}

/// [Technician] entity fields to define ObjectBox queries.
class Technician_ {
  /// See [Technician.id].
  static final id =
      obx.QueryIntegerProperty<Technician>(_entities[1].properties[0]);

  /// See [Technician.name].
  static final name =
      obx.QueryStringProperty<Technician>(_entities[1].properties[1]);
}

/// [Fault] entity fields to define ObjectBox queries.
class Fault_ {
  /// See [Fault.id].
  static final id = obx.QueryIntegerProperty<Fault>(_entities[2].properties[0]);

  /// See [Fault.name].
  static final name =
      obx.QueryStringProperty<Fault>(_entities[2].properties[1]);
}
