// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/brand.dart';
import 'models/fault.dart';
import 'models/service_item.dart';
import 'models/technician.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 6515935303844240695),
      name: 'Brand',
      lastPropertyId: const obx_int.IdUid(2, 8306864908252591682),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2676313357904241468),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8306864908252591682),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 2909156849271409078),
      name: 'Technician',
      lastPropertyId: const obx_int.IdUid(2, 5162456155613190713),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1359050086352987301),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5162456155613190713),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 2744046361083258745),
      name: 'Fault',
      lastPropertyId: const obx_int.IdUid(3, 6111243998934329244),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5173973318705152563),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7680505461191604277),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 2741046769985185864),
      name: 'ServiceItem',
      lastPropertyId: const obx_int.IdUid(19, 8819220676967962938),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4262077426002939470),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2249680476553143644),
            name: 'invoiceId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2502521965018990081),
            name: 'customerName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7535339852029768487),
            name: 'phoneNumber',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1875695528495847037),
            name: 'brandId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 4221880691690939450),
            relationTarget: 'Brand'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3722695806382409190),
            name: 'model',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 8136006091579036852),
            name: 'imei',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 7345205381407651702),
            name: 'issueDate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 4084403865013740571),
            name: 'technicianId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(3, 7823934307923419775),
            relationTarget: 'Technician'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 5206207293693681233),
            name: 'expense',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 4542060225975295651),
            name: 'servicePrice',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 7614448204599981215),
            name: 'simIncluded',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 3066888949636024165),
            name: 'sdIncluded',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 4582928756822897928),
            name: 'remark',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 7303596316115434591),
            name: 'status',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 1448402599571096960),
            name: 'location',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 3307281162366130143),
            name: 'deliveryDate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 8819220676967962938),
            name: 'isTrash',
            type: 1,
            flags: 8,
            indexId: const obx_int.IdUid(4, 8248569735318786504))
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(1, 1616147930685325004),
            name: 'faults',
            targetId: const obx_int.IdUid(4, 2744046361083258745))
      ],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(5, 2741046769985185864),
      lastIndexId: const obx_int.IdUid(4, 8248569735318786504),
      lastRelationId: const obx_int.IdUid(1, 1616147930685325004),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [7379893704960386916],
      retiredIndexUids: const [8701390231569931816],
      retiredPropertyUids: const [
        500841533034733396,
        2519385740775266796,
        6111243998934329244,
        8035667359138108551
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Brand: obx_int.EntityDefinition<Brand>(
        model: _entities[0],
        toOneRelations: (Brand object) => [],
        toManyRelations: (Brand object) => {},
        getId: (Brand object) => object.id,
        setId: (Brand object, int id) {
          object.id = id;
        },
        objectToFB: (Brand object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = Brand(id: idParam, name: nameParam);

          return object;
        }),
    Technician: obx_int.EntityDefinition<Technician>(
        model: _entities[1],
        toOneRelations: (Technician object) => [],
        toManyRelations: (Technician object) => {},
        getId: (Technician object) => object.id,
        setId: (Technician object, int id) {
          object.id = id;
        },
        objectToFB: (Technician object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = Technician(id: idParam, name: nameParam);

          return object;
        }),
    Fault: obx_int.EntityDefinition<Fault>(
        model: _entities[2],
        toOneRelations: (Fault object) => [],
        toManyRelations: (Fault object) => {},
        getId: (Fault object) => object.id,
        setId: (Fault object, int id) {
          object.id = id;
        },
        objectToFB: (Fault object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = Fault(id: idParam, name: nameParam);

          return object;
        }),
    ServiceItem: obx_int.EntityDefinition<ServiceItem>(
        model: _entities[3],
        toOneRelations: (ServiceItem object) =>
            [object.brand, object.technician],
        toManyRelations: (ServiceItem object) =>
            {obx_int.RelInfo<ServiceItem>.toMany(1, object.id): object.faults},
        getId: (ServiceItem object) => object.id,
        setId: (ServiceItem object, int id) {
          object.id = id;
        },
        objectToFB: (ServiceItem object, fb.Builder fbb) {
          final customerNameOffset = fbb.writeString(object.customerName);
          final phoneNumberOffset = fbb.writeString(object.phoneNumber);
          final modelOffset = fbb.writeString(object.model);
          final imeiOffset = fbb.writeString(object.imei);
          final issueDateOffset = fbb.writeString(object.issueDate);
          final remarkOffset =
              object.remark == null ? null : fbb.writeString(object.remark!);
          final statusOffset = fbb.writeString(object.status);
          final locationOffset = fbb.writeString(object.location);
          final deliveryDateOffset = object.deliveryDate == null
              ? null
              : fbb.writeString(object.deliveryDate!);
          fbb.startTable(20);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.invoiceId);
          fbb.addOffset(2, customerNameOffset);
          fbb.addOffset(3, phoneNumberOffset);
          fbb.addInt64(4, object.brand.targetId);
          fbb.addOffset(5, modelOffset);
          fbb.addOffset(6, imeiOffset);
          fbb.addOffset(7, issueDateOffset);
          fbb.addInt64(8, object.technician.targetId);
          fbb.addInt64(9, object.expense);
          fbb.addInt64(10, object.servicePrice);
          fbb.addBool(11, object.simIncluded);
          fbb.addBool(12, object.sdIncluded);
          fbb.addOffset(13, remarkOffset);
          fbb.addOffset(14, statusOffset);
          fbb.addOffset(15, locationOffset);
          fbb.addOffset(16, deliveryDateOffset);
          fbb.addBool(18, object.isTrash);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final invoiceIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final customerNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final phoneNumberParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final modelParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final imeiParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final issueDateParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final deliveryDateParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 36);
          final expenseParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 22);
          final servicePriceParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 24);
          final simIncludedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 26, false);
          final sdIncludedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 28, false);
          final remarkParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 30);
          final statusParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 32, '');
          final locationParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 34, '');
          final isTrashParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 40, false);
          final object = ServiceItem(
              id: idParam,
              invoiceId: invoiceIdParam,
              customerName: customerNameParam,
              phoneNumber: phoneNumberParam,
              model: modelParam,
              imei: imeiParam,
              issueDate: issueDateParam,
              deliveryDate: deliveryDateParam,
              expense: expenseParam,
              servicePrice: servicePriceParam,
              simIncluded: simIncludedParam,
              sdIncluded: sdIncludedParam,
              remark: remarkParam,
              status: statusParam,
              location: locationParam,
              isTrash: isTrashParam);
          object.brand.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.brand.attach(store);
          object.technician.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          object.technician.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<ServiceItem>(object.faults,
              store, obx_int.RelInfo<ServiceItem>.toMany(1, object.id));
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Brand] entity fields to define ObjectBox queries.
class Brand_ {
  /// See [Brand.id].
  static final id = obx.QueryIntegerProperty<Brand>(_entities[0].properties[0]);

  /// See [Brand.name].
  static final name =
      obx.QueryStringProperty<Brand>(_entities[0].properties[1]);
}

/// [Technician] entity fields to define ObjectBox queries.
class Technician_ {
  /// See [Technician.id].
  static final id =
      obx.QueryIntegerProperty<Technician>(_entities[1].properties[0]);

  /// See [Technician.name].
  static final name =
      obx.QueryStringProperty<Technician>(_entities[1].properties[1]);
}

/// [Fault] entity fields to define ObjectBox queries.
class Fault_ {
  /// See [Fault.id].
  static final id = obx.QueryIntegerProperty<Fault>(_entities[2].properties[0]);

  /// See [Fault.name].
  static final name =
      obx.QueryStringProperty<Fault>(_entities[2].properties[1]);
}

/// [ServiceItem] entity fields to define ObjectBox queries.
class ServiceItem_ {
  /// See [ServiceItem.id].
  static final id =
      obx.QueryIntegerProperty<ServiceItem>(_entities[3].properties[0]);

  /// See [ServiceItem.invoiceId].
  static final invoiceId =
      obx.QueryIntegerProperty<ServiceItem>(_entities[3].properties[1]);

  /// See [ServiceItem.customerName].
  static final customerName =
      obx.QueryStringProperty<ServiceItem>(_entities[3].properties[2]);

  /// See [ServiceItem.phoneNumber].
  static final phoneNumber =
      obx.QueryStringProperty<ServiceItem>(_entities[3].properties[3]);

  /// See [ServiceItem.brand].
  static final brand =
      obx.QueryRelationToOne<ServiceItem, Brand>(_entities[3].properties[4]);

  /// See [ServiceItem.model].
  static final model =
      obx.QueryStringProperty<ServiceItem>(_entities[3].properties[5]);

  /// See [ServiceItem.imei].
  static final imei =
      obx.QueryStringProperty<ServiceItem>(_entities[3].properties[6]);

  /// See [ServiceItem.issueDate].
  static final issueDate =
      obx.QueryStringProperty<ServiceItem>(_entities[3].properties[7]);

  /// See [ServiceItem.technician].
  static final technician = obx.QueryRelationToOne<ServiceItem, Technician>(
      _entities[3].properties[8]);

  /// See [ServiceItem.expense].
  static final expense =
      obx.QueryIntegerProperty<ServiceItem>(_entities[3].properties[9]);

  /// See [ServiceItem.servicePrice].
  static final servicePrice =
      obx.QueryIntegerProperty<ServiceItem>(_entities[3].properties[10]);

  /// See [ServiceItem.simIncluded].
  static final simIncluded =
      obx.QueryBooleanProperty<ServiceItem>(_entities[3].properties[11]);

  /// See [ServiceItem.sdIncluded].
  static final sdIncluded =
      obx.QueryBooleanProperty<ServiceItem>(_entities[3].properties[12]);

  /// See [ServiceItem.remark].
  static final remark =
      obx.QueryStringProperty<ServiceItem>(_entities[3].properties[13]);

  /// See [ServiceItem.status].
  static final status =
      obx.QueryStringProperty<ServiceItem>(_entities[3].properties[14]);

  /// See [ServiceItem.location].
  static final location =
      obx.QueryStringProperty<ServiceItem>(_entities[3].properties[15]);

  /// See [ServiceItem.deliveryDate].
  static final deliveryDate =
      obx.QueryStringProperty<ServiceItem>(_entities[3].properties[16]);

  /// See [ServiceItem.isTrash].
  static final isTrash =
      obx.QueryBooleanProperty<ServiceItem>(_entities[3].properties[17]);

  /// see [ServiceItem.faults]
  static final faults =
      obx.QueryRelationToMany<ServiceItem, Fault>(_entities[3].relations[0]);
}
